name: Fly Deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  check:
    name: Deno checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Typecheck
        run: deno check ./src/main.js
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Deploy to fly.io 
        uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: flyctl secrets unset GMAIL_PASSWORD
      # - run: flyctl secrets set GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}
      # - run: flyctl secrets set ETSY_API_KEY=${{ secrets.ETSY_API_KEY }}
      - run: flyctl deploy --remote-only
