name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        # - run: flyctl secrets unset GMAIL_PASSWORD
        # - run: flyctl secrets set GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}
        # - run: flyctl secrets set ETSY_API_KEY=${{ secrets.ETSY_API_KEY }}
        - run: flyctl deploy --remote-only
