name: Update Fly Secrets
on:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  update-fly-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets --detach unset GMAIL_PASSWORD ETSY_API_KEY
      - run: flyctl secrets set GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} ETSY_API_KEY=${{ secrets.ETSY_API_KEY }}
