name: Update Fly Secrets
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Fly Secrets'
        default: 'World'
        required: true
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  update-fly-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets unset GMAIL_PASSWORD ETSY_API_KEY
      - run: flyctl secrets set GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} ETSY_API_KEY=${{ secrets.ETSY_API_KEY }}
